{#
Copyright 2019 Nokia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
#}
---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: registry
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: registry
  template:
    metadata:
      annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "network":"flannel"
            }
          ]
      labels:
        name: registry
    spec:
      priorityClassName: "system-cluster-critical"
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: caas_master
      securityContext:
        runAsUser: {{ caas.uid.dockerreg }}
      containers:
        - name: registry
          image: {{ container_image_names | select('search', '/registry:') | list | last }}
          env:
            - name: INTERFACE_NAME
              value: "{{ caas.internal_flannel_interface }}"
            - name: REGISTRY_PORT
              value: "{{ caas.registry_port }}"
            - name: REGISTRY_CONFIG
              value: /etc/docker-registry/docker-registry-main-config.yml
          resources:
            requests:
              cpu: "10m"
          volumeMounts:
            - name: time-mount
              mountPath: /etc/localtime
              readOnly: true
            - name: config
              mountPath: /etc/docker-registry/
              readOnly: true
            - name: store
              mountPath: {{ caas.registry_directory }}
            - name: ca
              mountPath: /etc/ssl/certs/
              readOnly: true
      volumes:
        - name: time-mount
          hostPath:
            path: /etc/localtime
        - name: config
          hostPath:
            path: /etc/docker-registry/
        - name: store
          hostPath:
            path: {{ caas.registry_directory }}
        - name: ca
          hostPath:
            path: /etc/openssl/
